import type { Metadata } from "next";
import type { RouteInfo } from "./routes";
import { SITE_NAME } from "./site";

/**
 * 1200×630 is the size every card renderer expects, and the generated image has
 * to agree with the dimensions declared in the meta tags — a mismatch is what
 * makes clients letterbox or crop a card.
 */
export const OG_IMAGE_SIZE = { width: 1200, height: 630 };

/** The default share image, generated by `app/opengraph-image.tsx`. */
export const DEFAULT_OG_IMAGE = "/opengraph-image";

/** How that image is announced to anyone who cannot see it. */
export const DEFAULT_OG_IMAGE_ALT = "Lumina — Stellar network data, illuminated";

/** A per-account share image, generated by `app/accounts/[address]/opengraph-image.tsx`. */
export function accountOgImage(address: string): string {
  return `/accounts/${encodeURIComponent(address)}/opengraph-image`;
}

/**
 * A route's metadata is its identity in `lib/routes.ts` — its name and its one
 * sentence — plus, for a route that has one, a per-entity share image. So
 * `routeMetadata(EXPLORER)` is all a page has to say, and a route that is
 * missing from the inventory cannot be given a half-specified card by accident.
 */
export type RouteMetadataInput = RouteInfo & {
  /** A per-entity share image, where the route has one. */
  image?: string;
  imageAlt?: string;
};

function cardImages(url: string, alt: string) {
  return [{ url, width: OG_IMAGE_SIZE.width, height: OG_IMAGE_SIZE.height, alt }];
}

/**
 * The canonical link and the two card objects every route needs.
 *
 * They are built together, and from a function, because Next merges metadata
 * shallowly: a child segment that defines `openGraph` replaces the parent's
 * whole object rather than merging into it. A route that set only
 * `openGraph.title` would silently lose `siteName` and the image, and produce a
 * link preview with no picture in it — the failure this exists to prevent. The
 * root layout uses the same builder for its own defaults, so a route that
 * forgets to say anything still previews correctly.
 */
export function shareCard({ label, description, path, image, imageAlt }: RouteMetadataInput) {
  const title = label;
  // A route with no image of its own gets the site card, so the alt text is
  // the card's own description — appending the brand to a title that already
  // carries it would read "… — Lumina — Lumina".
  const images = cardImages(
    image ?? DEFAULT_OG_IMAGE,
    imageAlt ?? (image ? `${label} — ${SITE_NAME}` : DEFAULT_OG_IMAGE_ALT)
  );

  return {
    // `/events?contractId=X` and `/transactions?status=failed` are views of the
    // same page, not separate ones. Saying so keeps a filtered link from
    // competing with the route it filters in search results.
    alternates: { canonical: path },
    openGraph: {
      type: "website" as const,
      siteName: SITE_NAME,
      title,
      description,
      url: path,
      images,
    },
    twitter: {
      card: "summary_large_image" as const,
      title,
      description,
      images,
    },
  };
}

/** A route's complete metadata: its name, its description, and its share card. */
export function routeMetadata(input: RouteMetadataInput): Metadata {
  const { label, description } = input;
  return { title: label, description, ...shareCard(input) };
}
