/**
 * Turn the light palette in `app/globals.css` into `lib/generated/palette.ts`.
 *
 * `app/globals.css` is the one place a hex value may be authored. A couple of
 * consumers cannot read CSS custom properties at runtime — the generated
 * web-app manifest (JSON) and the Satori-rendered share cards — so this script
 * mirrors the light `:root` block into a TypeScript module they can import.
 *
 * `lib/palette.test.ts` re-parses the stylesheet and fails the build if this
 * file and `app/globals.css` ever disagree, so the mirror cannot go stale.
 *
 * Run via `npm run codegen`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = path.join(ROOT, "app", "globals.css");
const TARGET = path.join(ROOT, "lib", "generated", "palette.ts");

/** The light palette: every `--color-*` custom property declared in `:root`. */
export function parseLightPalette(css) {
  const rootBlock = css.match(/:root\s*\{([^}]*)\}/);
  if (!rootBlock) throw new Error("app/globals.css has no :root block");

  const palette = {};
  const declaration = /(--color-[a-z0-9-]+)\s*:\s*([^;]+);/gi;
  let match;
  while ((match = declaration.exec(rootBlock[1])) !== null) {
    palette[match[1]] = match[2].trim();
  }
  if (Object.keys(palette).length === 0) {
    throw new Error("app/globals.css declares no --color-* tokens");
  }
  return palette;
}

/** The generated module's source, byte-for-byte what lands on disk. */
export function renderPaletteModule(palette) {
  const entries = Object.entries(palette)
    .map(
      ([name, value]) => `  ${JSON.stringify(name)}: ${JSON.stringify(value)},`,
    )
    .join("\n");

  return `/* AUTO-GENERATED by scripts/gen-palette.mjs — do not edit.
 *
 * The light palette from app/globals.css, for the places CSS custom
 * properties cannot reach: the web-app manifest and the Satori share cards.
 * Regenerate with \`npm run codegen\`; lib/palette.test.ts fails on drift.
 */
export const colorTokens = {
${entries}
} as const;

export type ColorTokenName = keyof typeof colorTokens;
`;
}

const isMain =
  process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  const palette = parseLightPalette(readFileSync(SOURCE, "utf8"));
  writeFileSync(TARGET, renderPaletteModule(palette));
  console.log(
    `wrote ${path.relative(ROOT, TARGET)} (${Object.keys(palette).length} tokens)`,
  );
}
